DROP TABLE IF EXISTS Albums;
DROP TABLE IF EXISTS Artists;

CREATE TABLE Artists (
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255)
);



CREATE TABLE Albums (
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255),
  genre VARCHAR,
  artists_id INT4 REFERENCES artists(id)

);
